# Generated by Django 2.2.3 on 2019-07-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewMore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmore',
            name='title1',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
