# Generated by Django 2.2.3 on 2019-07-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewMore', '0002_reviewmore_title1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmore',
            name='title1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
